import pickle

from word_v_world import config

# get co-occurrence counts for these word pairs
adj_co_query = [('paper', 'airplane'),
                ('volunteer', 'ambulance'),
                ('carpenter', 'ant'),
                ('bean', 'bag'),
                ('traditional', 'bagpipe'),
                ('racquet', 'ball'),
                ('weather', 'balloon'),
                ('historic', 'barn'),
                ('empty', 'bathtub'),
                ('sugar', 'beet'),
                ('black', 'belt'),
                ('offroad', 'bike'),
                ('comic', 'book'),
                ('wild', 'buffalo'),
                ('sour', 'cabbage'),
                ('carrot', 'cake'),
                ('fresh', 'cantaloupe'),
                ('smelly', 'cat'),
                ('spicy', 'chicken'),
                ('disposable', 'cigarette'),
                ('saltwater', 'clam'),
                ('alto', 'clarinet'),
                ('bathroom', 'closet'),
                ('saltwater', 'cod'),
                ('crunchy', 'corn'),
                ('uncomfortable', 'couch'),
                ('timid', 'cougar'),
                ('giant', 'crab'),
                ('underwater', 'dolphin'),
                ('golden', 'eagle'),
                ('glass', 'elevator'),
                ('silent', 'elk'),
                ('acoustic', 'flute'),
                ('bass', 'guitar'),
                ('dwarf', 'hamster'),
                ('orchestral', 'harp'),
                ('teflon', 'harpoon'),
                ('black', 'hawk'),
                ('cookie', 'jar'),
                ('tight', 'jeans'),
                ('mandarin', 'orange'),
                ('sour', 'peach'),
                ('fountain', 'pen'),
                ('grey', 'pheasant'),
                ('rhubarb', 'pie'),
                ('cuddly', 'pig'),
                ('automatic', 'pistol'),
                ('adjustable', 'pliers'),
                ('overhead', 'projector'),
                ('fluffy', 'rabbit'),
                ('juicy', 'radish'),
                ('serrated', 'scissors'),
                ('electric', 'scooter'),
                ('domestic', 'sheep'),
                ('pirate', 'ship'),
                ('teflon', 'skillet'),
                ('glass', 'skyscraper'),
                ('plaid', 'sock'),
                ('miniature', 'surfboard'),
                ('tennis', 'table'),
                ('delicious', 'tangerine'),
                ('circus', 'tent'),
                ('commuter', 'train'),
                ('toy', 'tricycle'),
                ('giant', 'turtle'),
                ('exterior', 'wall')]


adj_fe_query = [('metal', 'airplane'),
                ('fast', 'ambulance'),
                ('small', 'ant'),
                ('colored', 'bag'),
                ('musical', 'bagpipe'),
                ('round', 'ball'),
                ('colorful', 'balloon'),
                ('smelly', 'barn'),
                ('white', 'bathtub'),
                ('purple', 'beet'),
                ('thin', 'belt'),
                ('metal', 'bike'),
                ('hard', 'book'),
                ('furry', 'buffalo'),
                ('green', 'cabbage'),
                ('sweet', 'cake'),
                ('wet', 'cantaloupe'),
                ('domestic', 'cat'),
                ('flightless', 'chicken'),
                ('unhealthy', 'cigarette'),
                ('hard', 'clam'),
                ('black', 'clarinet'),
                ('dark', 'closet'),
                ('edible', 'cod'),
                ('edible', 'corn'),
                ('heavy', 'couch'),
                ('vicious', 'cougar'),
                ('red', 'crab'),
                ('intelligent', 'dolphin'),
                ('bald', 'eagle'),
                ('electrical', 'elevator'),
                ('fast', 'elk'),
                ('silver', 'flute'),
                ('musical', 'guitar'),
                ('soft', 'hamster'),
                ('classical', 'harp'),
                ('long', 'harpoon'),
                ('large', 'hawk'),
                ('transparent', 'jar'),
                ('durable', 'jeans'),
                ('juicy', 'orange'),
                ('sweet', 'peach'),
                ('thin', 'pen'),
                ('edible', 'pheasant'),
                ('good', 'pie'),
                ('pink', 'pig'),
                ('lethal', 'pistol'),
                ('steel', 'pliers'),
                ('hot', 'projector'),
                ('small', 'rabbit'),
                ('spicy', 'radish'),
                ('sharp', 'scissors'),
                ('small', 'scooter'),
                ('white', 'sheep'),
                ('large', 'ship'),
                ('iron', 'skillet'),
                ('large', 'skyscraper'),
                ('cotton', 'sock'),
                ('fiberglass', 'surfboard'),
                ('flat', 'table'),
                ('juicy', 'tangerine'),
                ('portable', 'tent'),
                ('loud', 'train'),
                ('fun', 'tricycle'),
                ('slow', 'turtle'),
                ('flat', 'wall')]


ass_co_query = [('hanger', 'airplane'),
                ('paramedic', 'ambulance'),
                ('farm', 'ant'),
                ('socks', 'bag'),
                ('kilt', 'bagpipe'),
                ('bat', 'ball'),
                ('kite', 'balloon'),
                ('ranch', 'barn'),
                ('toilet', 'bathtub'),
                ('zucchini', 'beet'),
                ('trousers', 'belt'),
                ('rider', 'bike'),
                ('publisher', 'book'),
                ('bison', 'buffalo'),
                ('cauliflower', 'cabbage'),
                ('cookie', 'cake'),
                ('honeydew', 'cantaloupe'),
                ('hyena', 'cat'),
                ('pork', 'chicken'),
                ('ashtray', 'cigarette'),
                ('oyster', 'clam'),
                ('saxophone', 'clarinet'),
                ('broom', 'closet'),
                ('mackerel', 'cod'),
                ('beans', 'corn'),
                ('bed', 'couch'),
                ('coyote', 'cougar'),
                ('lobster', 'crab'),
                ('whale', 'dolphin'),
                ('owl', 'eagle'),
                ('escalator', 'elevator'),
                ('moose', 'elk'),
                ('oboe', 'flute'),
                ('rhythm', 'guitar'),
                ('rat', 'hamster'),
                ('orchestra', 'harp'),
                ('tomahawk', 'harpoon'),
                ('buzzard', 'hawk'),
                ('dishwasher', 'jar'),
                ('t-shirt', 'jeans'),
                ('grapefruit', 'orange'),
                ('nectarine', 'peach'),
                ('pencil', 'pen'),
                ('peacock', 'pheasant'),
                ('cookie', 'pie'),
                ('rooster', 'pig'),
                ('shotgun', 'pistol'),
                ('screwdriver', 'pliers'),
                ('camera', 'projector'),
                ('squirrel', 'rabbit'),
                ('turnip', 'radish'),
                ('crayons', 'scissors'),
                ('motorcycle', 'scooter'),
                ('flock', 'sheep'),
                ('merchant', 'ship'),
                ('spatula', 'skillet'),
                ('plaza', 'skyscraper'),
                ('sandal', 'sock'),
                ('kite', 'surfboard'),
                ('napkin', 'table'),
                ('grapefruit', 'tangerine'),
                ('shelter', 'tent'),
                ('station', 'train'),
                ('sleigh', 'tricycle'),
                ('alligator', 'turtle'),
                ('curtain', 'wall')]

ass_fe_query = [('passenger', 'airplane'),
                ('injury', 'ambulance'),
                ('ground', 'ant'),
                ('store', 'bag'),
                ('music', 'bagpipe'),
                ('sport', 'ball'),
                ('clown', 'balloon'),
                ('animal', 'barn'),
                ('bubble', 'bathtub'),
                ('garden', 'beet'),
                ('fashion', 'belt'),
                ('race', 'bike'),
                ('library', 'book'),
                ('cow', 'buffalo'),
                ('coleslaw', 'cabbage'),
                ('candle', 'cake'),
                ('tree', 'cantaloupe'),
                ('mouse', 'cat'),
                ('farm', 'chicken'), # farm or grain
                ('lighter', 'cigarette'),
                ('ocean', 'clam'),
                ('orchestra', 'clarinet'),
                ('clothing', 'closet'),
                ('water', 'cod'),
                ('butter', 'corn'),
                ('television', 'couch'),
                ('jungle', 'cougar'),
                ('sand', 'crab'),
                ('fish', 'dolphin'),
                ('nest', 'eagle'),
                ('building', 'elevator'),
                ('forest', 'elk'),
                ('air', 'flute'),
                ('band', 'guitar'),
                ('cage', 'hamster'),
                ('angel', 'harp'),
                ('boat', 'harpoon'),
                ('rodent', 'hawk'),
                ('jam', 'jar'),
                ('person', 'jeans'),
                ('vitamin', 'orange'),
                ('tree', 'peach'),
                ('paper', 'pen'),
                ('egg', 'pheasant'),
                ('oven', 'pie'),
                ('ham', 'pig'),
                ('police', 'pistol'),
                ('toolbox', 'pliers'),
                ('screen', 'projector'),
                ('carrot', 'rabbit'),
                ('salad', 'radish'),
                ('paper', 'scissors'),
                ('helmet', 'scooter'),
                ('meat', 'sheep'),
                ('captain', 'ship'),
                ('food', 'skillet'),
                ('office', 'skyscraper'),
                ('foot', 'sock'),
                ('wave', 'surfboard'),
                ('chair', 'table'),
                ('tree', 'tangerine'),
                ('protection', 'tent'),
                ('coal', 'train'),
                ('sidewalk', 'tricycle'),
                ('land', 'turtle'),
                ('picture', 'wall')]


part_co_query = [('pillow', 'airplane'),
                 ('doorknob', 'ambulance'),
                 ('tentacle', 'ant'),
                 ('strap', 'bag'),
                 ('reed', 'bagpipe'),
                 ('seam', 'ball'),
                 ('basket', 'balloon'),
                 ('roof', 'barn'),
                 ('faucet', 'bathtub'),
                 ('seed', 'beet'),
                 ('clasp', 'belt'),
                 ('rack', 'bike'),
                 ('chapter', 'book'),
                 ('hump', 'buffalo'),
                 ('stalk', 'cabbage'),
                 ('layer', 'cake'),
                 ('rind', 'cantaloupe'),
                 ('fur', 'cat'),
                 ('breast', 'chicken'),
                 ('butt', 'cigarette'),
                 ('shell', 'clam'),
                 ('mouthpiece', 'clarinet'),
                 ('timer', 'closet'),
                 ('liver', 'cod'),
                 ('starch', 'corn'),
                 ('foam', 'couch'),
                 ('paw', 'cougar'),
                 ('meat', 'crab'),
                 ('flipper', 'dolphin'),
                 ('talon', 'eagle'),
                 ('shaft', 'elevator'),
                 ('hump', 'elk'),
                 ('mouthpiece', 'flute'),
                 ('slide', 'guitar'),
                 ('snout', 'hamster'),
                 ('pedal', 'harp'),
                 ('missile', 'harpoon'),
                 ('talon', 'hawk'),
                 ('lid', 'jar'),
                 ('seam', 'jeans'),
                 ('rind', 'orange'),
                 ('fuzz', 'peach'),
                 ('ink', 'pen'),
                 ('feather', 'pheasant'),
                 ('filling', 'pie'),
                 ('meat', 'pig'),
                 ('barrel', 'pistol'),
                 ('clamp', 'pliers'),
                 ('lamp', 'projector'),
                 ('fur', 'rabbit'),
                 ('bulb', 'radish'),
                 ('hinge', 'scissors'),
                 ('gasoline', 'scooter'),
                 ('milk', 'sheep'),
                 ('cargo', 'ship'),
                 ('lid', 'skillet'),
                 ('concrete', 'skyscraper'),
                 ('toe', 'sock'),
                 ('cord', 'surfboard'),
                 ('drawer', 'table'),
                 ('juice', 'tangerine'),
                 ('peg', 'tent'),
                 ('whistle', 'train'),
                 ('brake', 'tricycle'),
                 ('shell', 'turtle'),
                 ('graffiti', 'wall')]

part_fe_query = [('wing', 'airplane'),
                 ('light', 'ambulance'),
                 ('antenna', 'ant'),
                 ('handle', 'bag'),
                 ('hole', 'bagpipe'),
                 ('surface', 'ball'),
                 ('air', 'balloon'),
                 ('door', 'barn'),
                 ('plug', 'bathtub'),
                 ('leaf', 'beet'),
                 ('material', 'belt'),
                 ('bar', 'bike'),
                 ('word', 'book'),
                 ('hair', 'buffalo'),
                 ('leaf', 'cabbage'),
                 ('candle', 'cake'),
                 ('seed', 'cantaloupe'),
                 ('paw', 'cat'),
                 ('beak', 'chicken'),
                 ('filter', 'cigarette'),
                 ('pearl', 'clam'),
                 ('key', 'clarinet'),
                 ('face', 'closet'),
                 ('fin', 'cod'),
                 ('ear', 'corn'),
                 ('pillow', 'couch'),
                 ('tail', 'cougar'),
                 ('pincher', 'crab'),
                 ('fin', 'dolphin'),
                 ('feather', 'eagle'),
                 ('button', 'elevator'),
                 ('antler', 'elk'),
                 ('hole', 'flute'),
                 ('hole', 'guitar'),
                 ('tail', 'hamster'),
                 ('string', 'harp'),
                 ('point', 'harpoon'),
                 ('claw', 'hawk'),
                 ('label', 'jar'),
                 ('zipper', 'jeans'),
                 ('seed', 'orange'),
                 ('pit', 'peach'),
                 ('cap', 'pen'),
                 ('beak', 'pheasant'),
                 ('crush', 'pie'),
                 ('snout', 'pig'),
                 ('trigger', 'pistol'),
                 ('nose', 'pliers'),
                 ('light', 'projector'),
                 ('ear', 'rabbit'),
                 ('leaf', 'radish'),
                 ('blade', 'scissors'),
                 ('wheel', 'scooter'),
                 ('wool', 'sheep'),
                 ('deck', 'ship'),
                 ('handle', 'skillet'),
                 ('elevator', 'skyscraper'),
                 ('material', 'sock'),
                 ('fin', 'surfboard'),
                 ('leg', 'table'),
                 ('section', 'tangerine'),
                 ('pole', 'tent'),
                 ('car', 'train'),
                 ('wheel', 'tricycle'),
                 ('head', 'turtle'),
                 ('paint', 'wall')]


act_co_query = [('manufacture', 'airplane'),
                ('transported', 'ambulance'),
                ('burrowed', 'ant'),
                ('dripped', 'bag'),
                ('tuned', 'bagpipe'),
                ('kicked', 'ball'),
                ('inflated', 'balloon'),
                ('hibernated', 'barn'),
                ('relaxed', 'bathtub'),
                ('harvested', 'beet'),
                ('fastened', 'belt'),
                ('wobbled', 'bike'),
                ('published', 'book'),
                ('hid', 'buffalo'),
                ('pickled', 'cabbage'),
                ('sliced', 'cake'),
                ('sliced', 'cantaloupe'),
                ('bred', 'cat'),
                ('garnished', 'chicken'),
                ('inhaled', 'cigarette'),
                ('baked', 'clam'),
                ('whistled', 'clarinet'),
                ('hid', 'closet'),
                ('hooked', 'cod'),
                ('boiled', 'corn'),
                ('sat', 'couch'),
                ('inhabited', 'cougar'),
                ('boiled', 'crab'),
                ('kicked', 'dolphin'),
                ('soared', 'eagle'),
                ('lifted', 'elevator'),
                ('licked', 'elk'),
                ('whistled', 'flute'),
                ('led', 'guitar'),
                ('shredded', 'hamster'),
                ('tuned', 'harp'),
                ('harmed', 'harpoon'),
                ('dove', 'hawk'),
                ('broiled', 'jar'),
                ('sewed', 'jeans'),
                ('garnished', 'orange'),
                ('infested', 'peach'),
                ('dipped', 'pen'),
                ('inhabited', 'pheasant'),
                ('sliced', 'pie'),
                ('suckled', 'pig'),
                ('gripped', 'pistol'),
                ('tightened', 'pliers'),
                ('displayed', 'projector'),
                ('burrowed', 'rabbit'),
                ('grated', 'radish'),
                ('sharpened', 'scissors'),
                ('manufactured', 'scooter'),
                ('bred', 'sheep'),
                ('sunk', 'ship'),
                ('melted', 'skillet'),
                ('erected', 'skyscraper'),
                ('knit', 'sock'),
                ('paddled', 'surfboard'),
                ('sat', 'table'),
                ('flavored', 'tangerine'),
                ('fastened', 'tent'),
                ('rode', 'train'),
                ('stole', 'tricycle'),
                ('hibernated', 'turtle'),
                ('climbed', 'wall')]

act_fe_query = [('traveled', 'airplane'),
                ('rescued', 'ambulance'),
                ('bit', 'ant'),
                ('held', 'bag'),
                ('marched', 'bagpipe'),
                ('played', 'ball'),
                ('floated', 'balloon'),
                ('stored', 'barn'),
                ('bathed', 'bathtub'),
                ('ate', 'beet'),
                ('held', 'belt'),
                ('exercised', 'bike'),
                ('stored', 'book'),
                ('ran', 'buffalo'),
                ('grew', 'cabbage'),
                ('ate', 'cake'),
                ('grew', 'cantaloupe'),
                ('ate', 'cat'),
                ('flew', 'chicken'),
                ('smoked', 'cigarette'),
                ('lived', 'clam'),
                ('fingered', 'clarinet'),
                ('hung', 'closet'),
                ('swam', 'cod'),
                ('tasted', 'corn'),
                ('slept', 'couch'),
                ('lived', 'cougar'),
                ('walked', 'crab'),
                ('swam', 'dolphin'),
                ('flew', 'eagle'),
                ('carried', 'elevator'),
                ('hunted', 'elk'),
                ('blew', 'flute'),
                ('picked', 'guitar'),
                ('drank', 'hamster'),
                ('plucked', 'harp'),
                ('hunted', 'harpoon'),
                ('soared', 'hawk'),
                ('preserved', 'jar'),
                ('wore', 'jeans'),
                ('peeled', 'orange'),
                ('grew', 'peach'),
                ('wrote', 'pen'),
                ('laid', 'pheasant'),
                ('cut', 'pie'),
                ('squealed', 'pig'),
                ('fired', 'pistol'),
                ('pulled', 'pliers'),
                ('showed', 'projector'),
                ('hunted', 'rabbit'),
                ('tasted', 'radish'),
                ('cut', 'scissors'),
                ('pushed', 'scooter'),
                ('clipped', 'sheep'),
                ('sailed', 'ship'),
                ('heated', 'skillet'),
                ('owned', 'skyscraper'),
                ('wore', 'sock'),
                ('stood', 'surfboard'),
                ('dined', 'table'),
                ('peeled', 'tangerine'),
                ('slept', 'tent'),
                ('traveled', 'train'),
                ('rode', 'tricycle'),
                ('snapped', 'turtle'),
                ('held', 'wall')]

curious_query = [('metal', 'airplane'),
                 ('paper', 'airplane')]
# load in combined_ww2cf pickle
combined_ww2cf_path = config.LocalDirs.root / 'data' / 'combined_ww2cf.pkl'
combined_ww2cf = pickle.load(combined_ww2cf_path.open('rb'))

# for curiosity's sake
for pair in curious_query:
    print(pair, combined_ww2cf.get(pair, None))

# inspect and save to file queried co-occurrence counts for adj_co
# with (config.LocalDirs.root / 'data' / 'adj_co_query.txt').open('w') as f:
#     for pair in adj_co_query:
#         print(pair, combined_ww2cf.get(pair, None))
#         f.write(str((pair, combined_ww2cf.get(pair, None))) + '\n')
#
# # inspect and save to file queried co-occurrence counts for adj_fe
# with (config.LocalDirs.root / 'data' / 'adj_fe_query.txt').open('w') as f:
#     for pair in adj_fe_query:
#         print(pair, combined_ww2cf.get(pair, None))
#         f.write(str((pair, combined_ww2cf.get(pair, None))) + '\n')
#
# # inspect and save to file queried co-occurrence counts for ass_co
# with (config.LocalDirs.root / 'data' / 'ass_co_query.txt').open('w') as f:
#     for pair in ass_co_query:
#         print(pair, combined_ww2cf.get(pair, None))
#         f.write(str((pair, combined_ww2cf.get(pair, None))) + '\n')
#
# # inspect and save to file queried co-occurrence counts for ass_fe
# with (config.LocalDirs.root / 'data' / 'ass_fe_query.txt').open('w') as f:
#     for pair in ass_fe_query:
#         print(pair, combined_ww2cf.get(pair, None))
#         f.write(str((pair, combined_ww2cf.get(pair, None))) + '\n')
#
# # inspect and save to file queried co-occurrence counts for part_co
# with (config.LocalDirs.root / 'data' / 'part_co_query.txt').open('w') as f:
#     for pair in part_co_query:
#         print(pair, combined_ww2cf.get(pair, None))
#         f.write(str((pair, combined_ww2cf.get(pair, None))) + '\n')
#
# # inspect and save to file queried co-occurrence counts for part_fe
# with (config.LocalDirs.root / 'data' / 'part_fe_query.txt').open('w') as f:
#     for pair in part_fe_query:
#         print(pair, combined_ww2cf.get(pair, None))
#         f.write(str((pair, combined_ww2cf.get(pair, None))) + '\n')
#
# # inspect and save to file queried co-occurrence counts for act_co
# with (config.LocalDirs.root / 'data' / 'act_co_query.txt').open('w') as f:
#     for pair in act_co_query:
#         print(pair, combined_ww2cf.get(pair, None))
#         f.write(str((pair, combined_ww2cf.get(pair, None))) + '\n')
#
# # inspect and save to file queried co-occurrence counts for part_fe
# with (config.LocalDirs.root / 'data' / 'act_fe_query.txt').open('w') as f:
#     for pair in act_fe_query:
#         print(pair, combined_ww2cf.get(pair, None))
#         f.write(str((pair, combined_ww2cf.get(pair, None))) + '\n')
